services:
  db:
    image: mariadb
    container_name: monday-db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 3s
      interval: 5s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: monday-backend
    restart: always
    working_dir: "/backend"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3006:3000'
    volumes:
      - ./backend:/backend
    command: bash -c "npm run dev"

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: monday-frontend
    restart: always
    working_dir: "/frontend"
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
    command: bash -c "npm run dev"

volumes:
  db:
